/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package snakegame;

/**
 *
 * @author fabouchedid
 */
public class ScorePanel extends javax.swing.JPanel implements ScoreListener {

    /**
     * Creates new form ScorePanel
     */
    public ScorePanel() {
        initComponents();
    }

    public void setScore(Integer score) {
        this.totalScoreLabel.setText(score.toString());
    }
    
    public void setFoodScore(Integer score) {
        this.foodScoreLabel.setText(score.toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        totalScoreLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        foodScoreLabel = new javax.swing.JLabel();

        jLabel1.setText("Score");

        totalScoreLabel.setText("0");

        jLabel3.setText("Food");

        foodScoreLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(totalScoreLabel)))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(foodScoreLabel))
                    .addComponent(jLabel3))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalScoreLabel)
                    .addComponent(foodScoreLabel))
                .addContainerGap(248, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel foodScoreLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel totalScoreLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setScores(Integer score, Integer foodScore) {
        this.setScore(score);
        this.setFoodScore(foodScore);
    }
}
